services:
  - type: worker
    name: telegram-bot
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python QTVChatParallelBot.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: 7954920709:AAFNqMtIl4zxCTFAttG-l5DkcwIIYLE_yAY
      - key: ALLOWED_CHAT_ID
        value: 6696130463
      - key: NEWS_API_KEY
        value: af9b016f3f044a6f84453bbe1a526f0b
